# Generated by Django 4.0.3 on 2022-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofilepic_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profile_pic',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
