# Generated by Django 4.0.3 on 2022-06-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_userprofilepic_foreign_key_to_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profile_pic',
            field=models.ImageField(default='profile/img_avatar.png', upload_to='profile/'),
        ),
    ]
