# Generated by Django 4.0.3 on 2022-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_userprofilepic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profile_pic',
            field=models.ImageField(auto_created=True, blank=True, null=True, upload_to='profile/'),
        ),
    ]
