# Generated by Django 4.0.3 on 2022-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_userprofilepic_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
