# Generated by Django 4.0.3 on 2022-06-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_rename_user_userprofilepic_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilepic',
            old_name='author',
            new_name='user',
        ),
    ]
