# Generated by Django 4.0.3 on 2022-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_status_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
