# Generated by Django 4.0.3 on 2022-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
