# Generated by Django 4.0.3 on 2022-06-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_remove_post_favorite_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoneUserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('comment_text', models.TextField()),
                ('datetime_comment', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recommended', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nu_comment', to='Blog.post')),
            ],
        ),
    ]
