# Generated by Django 4.0.3 on 2022-06-08 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0012_alter_favorite_fav_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='fav_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_post', to='Blog.post'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
