# Generated by Django 4.0.3 on 2022-06-09 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_userprofilepic_post_related'),
        ('Blog', '0014_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_profile_avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofilepic'),
        ),
    ]
