# Generated by Django 4.0.3 on 2022-06-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_userprofilepic_foreign_key_to_post'),
        ('Blog', '0018_remove_comment_email_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_profile_pic',
            field=models.ForeignKey(default='profile/img_avatar.png', on_delete=django.db.models.deletion.CASCADE, to='account.userprofilepic'),
        ),
    ]
