# Generated by Django 4.0.3 on 2022-06-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_alter_post_author_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_profile_pic',
        ),
    ]
