# Generated by Django 4.0.3 on 2022-06-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_userprofilepic_profile_pic'),
        ('Blog', '0026_remove_post_author_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofilepic'),
        ),
    ]
