# Generated by Django 4.0.3 on 2022-06-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0034_alter_post_author_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_profile_avatar',
        ),
    ]
