# Generated by Django 4.0.3 on 2022-06-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0036_comment_email_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(null=True, upload_to='post_pic/'),
        ),
    ]
