# Generated by Django 4.0.3 on 2022-06-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0039_alter_favoritecomment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recommended',
        ),
    ]
