# Generated by Django 4.0.3 on 2022-06-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0040_remove_comment_recommended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteComment',
        ),
    ]
