# Generated by Django 4.0.3 on 2022-07-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0047_alter_comment_comment_text_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(),
        ),
    ]
