# Generated by Django 4.0.3 on 2022-07-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0052_comment_content_type_comment_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
