# Generated by Django 4.0.3 on 2022-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0054_remove_comment_content_type_remove_comment_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(null=True),
        ),
    ]
