# Generated by Django 4.0.3 on 2022-07-14 09:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0057_alter_comment_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
