# Generated by Django 4.0.3 on 2022-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('Blog', '0061_alter_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='none_user_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments_by_none_user', to='sessions.session'),
        ),
    ]
