# Generated by Django 4.0.3 on 2022-07-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0062_comment_none_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='none_user_likes',
        ),
    ]
