# Generated by Django 4.0.3 on 2022-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('Blog', '0064_comment_none_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='none_user_likes',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='liked_comments_by_none_user', to='sessions.session'),
        ),
    ]
