# Generated by Django 4.0.3 on 2022-07-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('Blog', '0067_comment_none_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='none_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
