# Generated by Django 4.0.3 on 2022-07-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0070_comment_none_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='none_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='none_user_likes',
        ),
    ]
