# Generated by Django 4.0.3 on 2022-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0072_noneusercomment_remove_comment_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoneUserComment',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
