# Generated by Django 4.0.3 on 2022-07-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0076_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
